---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---

#Load required packages
```{r}
library(tidyverse)
library(ggplot2)
library(lme4)
library(broom)
library(ggthemes)
library(MuMIn)

devtools::load_all(".")
```

#Load graph theme
```{r}
team_theme <- function() {list(
  
  theme(axis.line = element_line(color = "black"),
        text = element_text(size = 8, family = "Times"),
        panel.background = element_rect(fill = 'white', colour = 'black'),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.title = element_text(colour =  "black", size = 14, hjust = 0.5),
        legend.text = element_text(size = 12, family = "Times")),
  scale_colour_colorblind())
}
```
#Run linear model
```{r, fig.cap= "Figure 1:"}
base <- glm(log.oy ~ log.AFR , data=mammals_sub)
summary(base)
tidy(base, conf.int=TRUE)
broom::augment(base) %>%
    ggplot(aes(x=log.AFR, y=.fitted)) +
    geom_line() +
    geom_point(aes(x=log.AFR, y=log.oy)) +
    geom_line(aes(y=.fitted)) +
     labs(x = "ln (Age of First Reproduction)", y = "ln (Offspring per Year)")+
  team_theme()
```
#Run linear mixed effects model
```{r, fig.cap= "Figure 2: Figure 2 displays the linear mixed effects model of the ln of Age of First Reproduction versus the ln of Offspring per year. The x-axis is the ln transformed age of first reproduction in months. The y-axis is the ln transformed number of offspring produced on average over a year. The purple line is the general linear for all of the data points. The other 7 lines are the trends for the individal orders."}
b <- lmer(log.oy ~ log.AFR + (log.AFR | order), data=mammals_sub)
summary(b)
lme4::ranef(b)
tidy(b, conf.int=TRUE)
broom::augment(b) %>%
    ggplot(aes(x=log.AFR, y=.fixed)) +
    geom_line( color = 'Purple') +
    geom_point(aes(x=log.AFR, y=log.oy, color = order), alpha = 0.15) +
    geom_line(aes(y=.fitted, color=order))+
    labs(x = "ln (Age of First Reproduction )", y = "ln (Offspring per Year)")+
  team_theme()+
    theme(legend.title=element_blank())

```




#Compare fits of models
```{r}
MuMIn::model.sel(b, base, rank=AIC)
```

```{r}
 smoke <- matrix(c((-0.6037+-0.07162499),(-0.6037+-0.29501976),(-0.6037+-0.11174519),(-0.6037+ 0.25183326),(-0.6037+0.42672130),(-0.6037+-0.28274597),(-0.6037+0.08258135)),ncol=1,byrow=TRUE)
colnames(smoke) <- c("Slope")
 rownames(smoke) <- c("Artiodactyla", "Carnivora", "Cetacea", "Insectivora", "Lagomopha", "Primates", "Rodentia")
 smoke <- as.table(smoke)
 smoke
```

