---
title: "R Notebook"
output: html_notebook
---

#Load required packages
```{r}
library(tidyverse)
library(ggplot2)
library(lme4)
library(broom)
library(ggthemes)
library(MuMIn)

devtools::load_all(".")
```


#Load graph theme
```{r}
team_theme <- function() {list(
  
  theme(axis.line = element_line(color = "black"),
        text = element_text(size = 8, family = "Times"),
        panel.background = element_rect(fill = 'white', colour = 'black'),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.title = element_text(colour =  "black", size = 14, hjust = 0.5),
        legend.text = element_text(size = 12, family = "Times")),
  scale_colour_colorblind())
}
```
#Run linear mixed effects model
```{r}
fit <- lmer(log.oy ~ log.wm + (log.wm | order), data = mammals_sub)
summary(fit)
lme4::ranef(fit)
tidy(fit, conf.int = TRUE)
broom::augment(fit) %>%
    ggplot(aes(x = log.wm, y = .fixed)) +
    geom_line() +
    geom_point(aes(x = log.wm, y = log.oy, color = order), alpha = 0.15) +
    geom_line(aes(y = .fitted, color = order)) +
    team_theme() + ylab("ln(Number of offspring per year)") + xlab("ln(Weaning age (months))")
```
#Run linear model
```{r}
base <- glm(log.oy ~ log.wm , data=mammals_sub)
summary(base)
tidy(base, conf.int=TRUE)
broom::augment(base) %>%
    ggplot(aes(x=log.wm, y=.fitted)) +
    geom_line() +
    geom_point(aes(x=log.wm, y=log.oy)) +
    geom_line(aes(y=.fitted)) +
  team_theme()
```
#Compare fits of models
```{r}
MuMIn::model.sel(fit, base, rank=AIC)
```


