---
title: "R Notebook"
output: html_notebook
---

```{r}
bigorders %>%
    ggplot(aes(x=max..life.mo., y=AFR.mo.)) +
    geom_point() +
    geom_smooth(method='loess', alpha=0.5) +
    facet_wrap(~ order)
 
```

```{r}
install.packages("lme4")
```

```{r}
rodents <- mammals %>%
    filter(order == 'Rodentia')

primates <- mammals %>%
    filter(order == 'Primates')
```



```{r}
mammals %>%
    group_by(order) %>%
    tally() %>%
    filter(n > 100)

bigorders <- mammal_data %>%
    filter(order == 'Artiodactyla' | order == "Carnivora" | order == "Primates" | order == "Rodentia")

norodents <- mammals %>%
    filter(order == 'Artiodactyla' | order == "Carnivora" | order == "Primates")

nocarnivs <- mammals %>%
    filter(order == 'Artiodactyla' | order == "Primates" | order == "Rodentia")
```


```{r}
library(lme4)
library(Matrix)
```

```{r}
 a <- lmer(AFR.mo. ~ max..life.mo. + (max..life.mo. | family), data = rodents)
summary(a)
lme4::ranef(a)
library(broom)
tidy(a, conf.int=TRUE)
```


