---
title: "R Notebook"
output: html_notebook
---

## Discussion for Max Lifespan

    The present study has shown a negative correlation between the number of offspring produced per year and parental maximum lifespan in mammals (Figure 3). This correlation is expected as a result of parent offspring conflict. A longer maximum lifespan is associated with a longer period of reproductive activity (McNamara *et al.* 2009). Given that a parent should behave in a manner that maximizes the fitness of all of their offspring, both present and future (Hamilton 1964), parents who are reproductively active for a longer time should reproduce their per year offspring production and care, given the increased costs of a longer reproductively active lifespan. Parents who have longer reproductively active periods will want to allocate a higher proportion of their available resources towards future reproduction than parents who have a short reproductively active period (Trivers 1974). When a parent decides to re-allocate resources away from current reproduction, they are likely to reduce both the amount of care provided to each offspring and the number of offspring produced. 
    As reproductively active lifespan increases, there is the potential for intense parent-offspring conflict. Each offspring a mother produces will come with a cost, which will be manifested in a lower potential future reproductive ability. When reproductive lifespan is long, costs to future reproductive ability are undesirable, because a parent has a high number of potential future reproductive events, and compromising these will result in a lower fitness for a high proportion of their offspring. As such, parental care for individual offspring should be limited, because the cost-benefit ratio for each offspring will increase more quickly. Potential parent-offspring conflict could arise sooner, and is likely to be more intense, given that there is more at stake for the parent (Trivers 1974). 
    In mammals with shorter reproductively active lifespans, there is still the potential for parent-offspring conflict, but the conflict is likely to be more driven by sibling-sibling competition. Parents with shorter reproductively active lifespans will always be caring for a higher proportion of their entire pool of potential offspring than parents with longer reproductively active periods, and thus the cost of providing care will not be as high, given that they are not sacrificing the fitness of as many potential future offspring. However, because the number of offspring these parents produce in each reproductive event is higher, the energetic costs of care can become significant. Thus, parents are likely limiting the care provided to each current offspring, which is the basis for parent-offspring conflict. 
    

## Literature Cited

McNamara JM, Houston AI, Barta Z, Scheuerlein A, Fromhage L. 2009. Deterioration, death and the evolution of reproductive     constraint in late life. *Proc. R. Soc. B Biol 276(1675): 4061-4066.

