---
title: "Methods"
output:
  html_document: default
  html_notebook: default
---
## Data Description

This dataset was made available by Morgan S.K. Ernest from the depart of biology, University of New Mexico, Albuquerque, New Mexico, 87131 USA. The dataset is a compile of general life history characteristics of 17 placental nonvolant mammalian orders. The data was obtained from various literature sources starting from 1998 and is currently ongoing. These past literature sources have studied species from various trophic levels, and habitats, therefore in this dataset the life history characteristics were averaged to get rid of minor environmental/niche specific differences. The dataset represents all placental nonvolant mammalian orders including terrestrial and aquatic mammals, expect for the *Chiroptera* (bats) order for a total of 17 orders. The 17 orders and the number of species represented in each order in the dataset are *Artiodactyla* (161 species), *Carnivora* (197 species), *Cetacea* (55 species), *Dermoptera* (2 species), *Hydracoidea* (4 species), *Insectivora* (91 species), *Lagomorpha* (42 species), *Macroscelidea* (10 species), *Perissodactyla* (15 species), *Pholidota* (7 species), *Primates* (156 species), *Proboscidea* (2 species), *Rodentia* (665 species), *Scandentia* (7 species), *Sirenia* (5 species), *Tubulidentata* (1 species), and *Xenarthra* (20 species). The 9 life history characteristics represented in the dataset are: maximum lifespan (months) which is the oldest age recorded for a member of that species (male or female), age of first reproduction (months) which is the average age when a females first breeds, gestation time (months) which is the average length of time the fetus is in the womb, weaning age (months) which is the average age an offspring begins eating solid food , weaning mass (grams) which is the average mass of an offspring when they begins eating solid food, litter size which is the average number of offspring birthed in single liter, litters per a year which is the average number of litters birthed in a 12 month period, newborn mass (grams) which is the average weight of a newborn taken within 12 hours after birth, and adult body mass (grams) which is the average weight of non-pregnant adult females. 
