---
title: "R Notebook"
output: html_notebook
---

#Load required packages
```{r}
library(tidyverse)
library(lme4)
library(Matrix)
library(broom)
library(ggthemes)
```

#Import 'mammals.csv' dataset from data file in eeb430.2017.Python repo

#Filter data to include only orders with a large sample size
```{r}
mammals <- mammals
orders <- mammals %>%
    filter(order == 'Artiodactyla' | order == 'Carnivora' | order == 'Cetacea' | order == 'Insectivora' | order == 'Lagomorpha' | order == 'Primates' | order == 'Rodentia' )
```

#Create log-transformed data columns for variables to be used in model
```{r}
orders3 <- orders %>%
    mutate(offspring.year = litter_size * litters_inyear) %>%
    mutate(log.oy = log(offspring.year)) %>%
    mutate(log.wm = log(weaning_month))
```

#Load graph theme
```{r}
team_theme <- function() {list(
  
  theme(axis.line = element_line(color = "black"),
        text = element_text(size = 8, family = "Times"),
        panel.background = element_rect(fill = 'white', colour = 'black'),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.title = element_text(colour =  "black", size = 14, hjust = 0.5),
        legend.text = element_text(size = 12, family = "Times")),
  scale_colour_colorblind())
}
```

#Run mixed effects model using lme4
```{r}
d <- lmer(log.oy ~ log.wm + (log.wm | order), data = orders3)
summary(d)
lme4::ranef(d)
tidy(d, conf.int = TRUE)
broom::augment(d) %>%
    ggplot(aes(x = log.wm, y = .fixed)) +
    geom_line() +
    geom_point(aes(x = log.wm, y = log.oy, color = order)) +
    geom_line(aes(y = .fitted, color = order)) +
    team_theme()
```




