---
title: "UpdatedResultsDiscussionWeaning"
output: html_notebook
---

##Results 
According to the prediction of mixed-effects linear model, there is a negative relationship between the weaning age and the number of offspring across all orders (Fig. 1). Moreover, using orders as random effects significantly improves the model fit, compared to using generalized linear model, as indicated by the lower AIC value (Table 1). The overall linear trend across all orders appears to be negative for the weaning-number of offspring relationship. However, Rodentia, Insectivora and Primates show the most negative relationship with slopes being higher than 0.6 (Table 2). Additionally, despite all trends being negative there is order-specific variation in both the number of offspring, and weaning age (Fig. 1). Larger mammals tend to have less offspring and delay the weaning time, whereas small mammals produce more offspring, and wean fairly early (Fig. 1). 

```{r}
library(lme4)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(broom)

team_theme <- function() {list(
  
  theme(axis.line = element_line(color = "black"),
        text = element_text(size = 8, family = "Times"),
        panel.background = element_rect(fill = 'white', colour = 'black'),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.title = element_text(colour =  "black", size = 14, hjust = 0.5),
        legend.text = element_text(size = 12, family = "Times")),
  scale_colour_colorblind())
}


fit <- lmer(log.oy ~ log.wm + (log.wm | order), data = mammals_sub)
summary(fit)
lme4::ranef(fit)
tidy(fit, conf.int = TRUE)
broom::augment(fit) %>%
    ggplot(aes(x = log.wm, y = .fixed)) +
    geom_line() +
    geom_point(aes(x = log.wm, y = log.oy, color = order), alpha = 0.15) +
    geom_line(aes(y = .fitted, color = order)) +
    team_theme() + ylab("ln(Number of offspring per year)") + xlab("ln(Weaning age (months))")
```



## Discussion
### Weaning age

One of the biggest investments that a mother makes towards her offspring is lactation. In fact, lactation has been described as the most costly resource allocation (Gittleman and Thomspon 1988). As predicted by parent-offspring conflict (Trivers 1974), the ideal optima in reproductive decisions differ in parents and offspring. Since lactation is an important factor that requires resources from mother, it is crucial for the parents to determine for how long to nurse their offspring. Parents’ strategy aims at maximizing (future) reproduction without foregoing the needs of the current litter. Stearns (1989) described this as tradeoff between somatic and reproductive investments. From offspring’s perspective, prolonging the nursing/lactation period for as long as possible is the best strategy because transition from lactating to weaning imposes stress on the offsring. For example, separation from mother has been associated with increased amounts of cortisol in young otters (Malmkvist et al. 2016). 
In our data analysis, we found a negative correlation between the number of offspring a female has in one year, and the age at which her offspring are weaned, as is expected by the trade-off hypothesis (Trivers 1974). Moreover, out data shows clear distinction between mammals with high and low reproductive output (Fig. S4). Rodents are expected to have resources for more offspring, given that their investment in each litter is low. Previous research has found that increased period of lactation delays the time of birth of the next litter (Hedrich and Bullock 2004). This is an indication of the conflict of future and current offspring. As a result of that, and the fact that mice have relatively short life span (due to high metabolic rate (Hedrich and Bullock 2004)), mothers cannot allocate as many resources towards any given offspring, and therefore most rodents start weaning at approximately 2 months of age (Fig. S4). Mice also show an ability to adjust both the quality and quantity of produced milk according to litter size (Hedrich and Bullock 2004). Despite this, offspring reared in high litter batches usually have lower weight. This is consistent with what we observe in our data, and suggests that energy expenditure for lactation determines the amount of offspring the rodent produces. 
In contrast to rodents, animals with low life-time reproductive output (e.g. whales) show tendency to nurse their offspring for longer time (Fig. S4). In Cetacea, the weaning age is quite variable despite the low variance in the offspring number, and this suggests that determinants of resource allocation towards nursing in Cetacea could be species-specific. For instance, average nursing time in Odontea is around 2 years (Sergeant 1973), and this agrees with what we observe in our data. Additionally, maternal age influence nursing duration, as older mothers are more likely to invest more in offspring, both because probability of the next offspring declines with age (terminal investment hypothesis) and because older females have more resources, due to increased weight (Clutton-Brock 1984). We did not account for maternal age in our dataset, but these papers also support out initial prediction that reproductive output and resource allocation towards individual offspring are negatively correlated. 
According to the mixed effects model fit, one of the most negative relationships between weaning age and number of offspring is observed in primates. Previous research has demonstrated occurrence of parent-offspring conflict in almost all primates, and particularly in great apes the conflict has been described as “prolonged” and “intense” (Maestripieri 2009). In rhesus macaques, parent-offspring conflict is characterized by increased suckling demands by offspring, and rejection behaviour by mother (Gomendio 1990). Moreover, offspring can be successful in inhibiting the future reproduction of their mother, in cases when their demand for nursing is increased (Gomendio 1990). Our data suggest the same pattern, as increase in lactation allocation, and hence delayed transition from nursing to weaning is correlated with lower reproductive output in primates. Studies on Japanese macaques have found that mothers tend to decrease time allocated towards nursing, during mating season (Collinge 1987), which could be interpreted as a tradeoff between current and potential future offspring. However, there is no clear data on whether or not mother-offspring suckling relationship has any influence on the amount of offspring the mother conceives during the mating season. Hence, according to behavioural studies on primates, the likely conclusion that parent-offspring conflict is present in a wide range of primates. Moreover it is characterized by the increased conflicting encounters between mother and offspring, which seem to be especially prolonged in primates (Maestripieri 2009). 
