---
title: "Intro Outline"
output: html_notebook
---

## Intro Outline
- Basics of parent-offspring conflict --> Carter
- General mammal life history --> Smooj
- Post-birth development --> Farida
- Gestation --> Ben

## INTRODUCTION

### Parent-Offspring Conflict

    In the animal kingdom, individuals should behave in a manner that maximizes their overall fitness and reproductive success. This is most often manifested in the form of behaviors meant to maximize the fitness of every offspring an individual produces over the course of their life (Marshall & Uller 2007). Resources are distributed evenly across all of a parent's offspring because a parent is equally related to each of their offspring, and thus should attempt to ensure the fitness of each offspring is maximized (Hamilton 1964). Conversely, from the perspctive of the offspring, each individual is more related to itself than any of its siblings, and thus each offspring should want more resources allocated to it than a parent is willing to provide (Trivers 1974).
    
    Robert Trivers discussed the dynamics of parent-offspring conflict in terms of cost-benefit ratios. At birth, the interests of the parent and offspring align, because the offspring is capable of little on its own. Thus, it is in the parent's interest to provide as much care as possible to ensure the offspring's survival. However, as the offspring grows, the cost of providing resources increases for the parent, and the benefit decreases, since the offspring is somewhat able to feed itself. From the parent's perspective, care should be terminated when its costs and benefits are equal. From the offspring's perspective, care should be terminated when its costs are double its benefits. Conflict arises when the costs are between one and two times as great as the benefits (Trivers 1974).
    
    Both parents and offspring have been shown to utilize manipulative tactics when conflicts arise. In squamates, mothers have been shown to actively attempt to increase egg incubation temperatures in order to accelerate hatching and increase body size at hatch. The larger offspring are more precocial, and faster hatching times mean that mothers do not have to spend as long caring for their current set of offspring (Olsson & Shine 1997). There is extensive evidence of offspring using manipulative tactics, particularly in birds. Chicks are widely known to beg for food from their parents, particularly when parents decrease the amount of care they provide (Harper 1986).
    
### Mammalian Life Histories

    The present study utilizes a large published dataset to attempt to quantify evidence of parent-offspring conflict in mammals. The largest trade-off in the general mammalian life history involves the cost of reproduction. Investment in current reproductive efforts results in costs paid in both survival and potential future reproduction (Stearns 1989). Specific mammalian life histories can be described by the fast-slow continuum hypothesis, which places species along a continuum based on their reproductive rate and generation time. The fast end of the continuum is populated by species that mature early with high reproductive rates and short generation times, while the slow end contains species that take longer to mature, have lower reproductive rates and longer generation times (Oli 2004).
    
    Oli (2004) utilized published life history data from 138 mammal populations to attempt to place species along his fast-slow continuum, and found that species were evenly distributed across the entire continuum. 29 species were categorized as fast, 31 were slow, and 29 were placed centrally on the continuum. Species on either end of the continuum had a number of shared characters. The majority of fast species had relatively small body size, high fertility rates, and low survival rates. Contrarily, slow species tended to have larger body size, lower fertility rates, and higher survival rates.

    Species at both ends of Oli's continuum have had their reproductive life histories examined. Moore *et al.* (2016) examined reproductive fitness in golden-mantled ground squirrels, a species that falls at the fast end of Oli's continuum. They found evidence of a trade-off between delayed age of first reproduction and offspring survival rate. By delaying their age of first reproduction, parents experienced a decrease in individual fitness, but an increase in offspring survival rate. Offspring born to parents who became reproductively active earlier had a lower survival rate, but the parents had a higher individual fitness. Hadley *et al.* (2007) studied reproductive costs in Weddell seals, a slow species on Oli's continuum. These seals are intermittent breeders, and can wait several years between breeding events. Reproductive activity was shown to be associated with a decrease in individual survival. Breeding individuals were also less likely than non-breeding individuals to breed in the next season, suggesting that the costs of reproduction are quite high.

### Mammalian Gestation

    The majority of investment into offspring by to placental animals occurs during gestation. There is evidence of trade-offs with respect to gestation period length in mammals. In many bat species, there is a positive correlation between gestation period length and neonate size (Kurta & Kunz 1987). Individual fitness of the parents is forfeit as gestation time increases, due to survival costs while pregnant. Thus, there is potential for parent-offspring conflict as investment into gestation increases.
    
    Gestation time has also been shown to vary depending on whether placental neonates are altricial or precocial. Altricial young tend to require a higher level of maternal investment for a given gestation period than precocial young. Because of this, gestation periods in species that produce altricial young are shorter (Martin & MacLarnon 1985). Production of altricial young is often associated with an increase in overall reproductive output. A species that produces altricial young will tend to have a higher reproductive rate than a similar species that produces precocial young, due to the increased costs associated with the rearing of precocial young (Hennemann 1984).
    
    There is evidence of a trade-off between maternal investment in gestation and lactation. It has been observed that the cost of gestation is less than that of lactation (Gittleman & Thompson 1988). This is a potential source of parent-offspring conflict, given that altricial neonates require a relatively long lactation period (Hennemann 1984). There is a high degree of variation in the relative allocation of resources to either gestation or lactation across mammals, so inferences made about energetic expenditure by the mother or parent-offspring conflict over lactation period length must consider the species' life history. Furthermore, there is evidence that many trends related to gestation could be inaccurate due to the ubiquity of neonate body mass as a measure of development during gestation. Sacher and Staffeldt (1974) argue that neonate brain mass, rather than body mass, should be used to describe trends related to gestation. The brain has the slowest development rate of any organ, and the growth of other bodily tissues is limited by, but not necessarily always equal to, the rate of brain growth. 
    

### Post-Birth Resource Allocation

    The majority of parent-offspring conflict in mammals occurs post-birth. At this point in neonate development, the parent has already invested a sigificant amount of resources into their offspring, and will be attempting to decrease the amount of care they provide (Trivers 1974). As neonates grow, their energetic needs increase, and until they are effectively able to source their own nutrients, they will become increasingly dependent on their mother for nutrition via milk. Free-ranging dogs have a well-studied weaning conflict. Pups nurse from birth and weaning begins in their seventh week. At this point, the mother will refuse to nurse. It was observed that as the pups grew, their nursing attempts became more frequent, and the mothers' attempts to initiate nursing became less frequent (Paul & Bhadra 2017).
    
    There is evidence that female mammals will attempt to increase their milk production to accommodate larger litter sizes. Female house mice were observed to increase both the volume and nutrient content of their milk when they birthed larger litters (Kounig *et al.* 1988). However, this increase was not indefinite. The larger the litter got, the smaller the percent increase in nutrient content was. Neonates from larger litters had lower post-weaning body mass than those from smaller litters. This is evidence that parent-offspring conflict is likely more prevalent in larger litters, because it is more difficult for neonates to obtain the nutrients they require to not have a post-weaning fitness disadvantage when compared to neonates from smaller litters.
    
    Maternal size has a significant effect on lactation performance. In marmosets, it has been observed that smaller mothers produce milk with lower nutrient and fat content than larger mothers (Tardif *et al.* 2001). Smaller mothers also nurse their offspring less frequently. Smaller mothers are also more likely to lose further weight and less likely to be fertile in subsequent breeding seasons. This is grounds for parent-offspring conflict, because mothers are very clearly sacrificing future reproductive success to care for current offspring as well as individual health and fitness.
    
### Objectives
We should figure out Sunday exactly what we want to say about the purpose of this stuff. Like what we're trying to prove using our trends.

## Literature Cited

Gittleman J, Thompson S. 1988. Energy allocation in mammalian reproduction. *American Zoology* 28(3): 863-875.

Hadley GL, Rotella JJ, Garrott RA. 2007. Evaluation of reproductive costs for Weddell seals in Erebus Bay, Antarctica.     *Journal of Animal Ecology* 76(3): 448-458.

Hamilton WD. 1964. The genetical evolution of social behavior. I. *J. Theoret. Biol.* 7: 1-16.

Harper AB. 1986. The evolution of begging: Sibling competition and parent-offspring conflict. *The American Naturalist*     128(1): 99-114.

Hennemann WW. 1984. Intrinsic rates of natural increase of altricial and precocial eutherian mammals: the potential price     of precociality. *Oikos* 43(3): 363-368.

Kounig B, Riester J, Markl H. 1988. Maternal care in house mice (*Mus musculus*): II. The energy cost of lactation as a     function of litter size. *Journal of Zoology* 216(2): 195-210.

Kurta A, Kunz T. 1987. Size of bats at birth and maternal investment during pregnancy. *Zoological Symposium* 57: 79-106.

Marshall DJ, Uller T. 2007. When is a maternal effect adaptive? *Oikos* 116: 1957-1963.

Martin R, MacLarnon A. 1985. Gestation period, neonatal size and maternal investment in placental mammals. *Nature*         313(17): 220-223.

Moore JF, Wells CP, Van Vuren DH, Oli MK. 2016. Who pays? intra- vs inter-generational costs of reproduction. *Ecosphere*     7(2): e01236.

Oli M. 2004. The fast-slow continuum and mammalian life-history patterns: an empirical evaluation. *Basic and Applied        Ecology* 5(5): 449-463.

Olsson M, Shine R. 1997. The seasonal timing of oviposition in sand lizards (*Lacerta agilis*): Why earlier clutches are
    better. *Evolution* 52: 1861-1864.

Paul M, Bhadra A. 2017. Selfish pups: weaning conflict and milk theft in free-ranging dogs. *PLoS One* 12(2): e0170590.

Sacher G, Staffeldt E. 1974. Relation of gestation time to brain weight for placental mammals: implications for the         theory of vertebrate growth. *The American Naturalist* 108(963): 593-615.

Stearns SC. 1989. Trade-offs in life history evolution. *Functional Ecology* 3(3): 259-268.

Tardif SD, Power M, Oftedal OT, Power RA, Layne DG. 2001. Lactation, maternal behavior and infant growth in common         marmoset monkeys (*Callithrix jacchus*): effects of maternal size and litter size. *Behavioral Ecology and               Sociobiology* 51(1): 17-25.

Trivers RL. 1974. Parent-offspring conflict. *American Zoologist* 14(1): 249-264.


